apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-apache
    
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-apache
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-apache
    spec:
      containers:
      - name: {{.Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
