apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-apache
spec: 
  selector: 
    app: {{ .Release.Name }}-apache
  type: {{ .Values.service.type }}
  ports: 
    - name: http 
      port: {{ .Values.service.port }} 
      targetPort: 8080