apiVersion: v1 
kind: Service 
metadata: 
  name: frontend 
spec: 
  selector: 
    app: frontend 
  type: {{ .Values.servcie.type }}
  ports: 
    - name: http 
      port: {{ .Values.service.port }} 
      targetPort: 8080